### PR TITLE
system monitoring bash script - completed

### PR DESCRIPTION
**Pull request by Lishan997**
Created simple Bash script to monitor system resources (CPU, memory, and disk usage) and log the information to a file. The script will be executed every 10 minutes using a cron job

### CODE REVIEW

**Comment by tharinduk001** [comment]
Hi,

Thank you for your fantastic contribution to the Codeku Cloud and DevOps micro tasks! We truly appreciate your effort. However, we regret to inform you that this particular task cannot be approved due to a few errors. But don’t worry—this is just the beginning! There will be plenty of opportunities in the future, and we’re confident that you’ll succeed next time.

We encourage you to keep trying, and we wish you the very best of luck!

Warm regards,  
Team CoDeKu

**Comment by Lishan997** [comment]
Dear tharindu,

The reason I participate to this programm is to identify my issues and improve them, you have mentioned few errors in your message, could you please mentioned them, because those errors will help me to give good solution in the future. 

Thank you.

**Comment by tharinduk001** [comment]
Hi Mithila,

The reason for not selecting you is you have not included cron jobs, the
screenshots to verify and also the PR Message title (we cant identify the
project without clearly mentioning the task code). And the winner candidate
has performed well in all those areas. That's why we have to look very
carefully at all of these PRs as we need to choose only one best candidate.

Thanks.

**Comment by Lishan997** [comment]
Dear Tharindu,

I have few clarification about your reply I need to clarify further.

1. Not included crone job




These are the instructions to config the cron job as mention in the problem

According below screen shot





I did not see any expectation of the screen shot of the cron job in the
deliverables of your project instructions

According to below screenshot





2.my commit message might be not a proper commit message but i did not see
any specific instructions of commit message of the project guidelines

Thank you,
Mithila Lishan.

**Comment by tharinduk001** [comment]
See the documentation again.

**Comment by Lishan997** [comment]
Dear Tharindu,

I read instructions several time before raise the pull request , I think
now your time to read the instructions 😂😂.

Best regards,
Mithila Lishan.

**Comment by tharinduk001** [comment]
OK SORRY FOR ALL. SO WHAT ARE YOU SAY TO DO NOW? I CANT FIGHT WITH YOU MEN!
I Cant fighting you with a repo I have another work. You are talking in a
very aggressive way even on the whatsapp .

**Comment by tharinduk001** [comment]
If you are not satisfying with these work you can stop working on those.
The selection is not done by me! There is a selection board also. So please
be left from the rest of work

**Comment by Lishan997** [comment]
Dear Tharindu,

I know this is grate opportunity to improve our devops related knowledge

And I wanted to mention that I don't want to fight with you.

This is not fight tharindu, I am trying to understand where I have done
wrong , things which you are saying are not matched with the instructions
that's my problem.

I did not know you are not responsible for this, that's why I keep sending
emails to you and questioning you.

This is my last email regarding this problem.

Have grate night!

Thank you,
Mithila Lishan.

**Comment by tharinduk001** [comment]
Hi Mithila,

Thanks for understanding Mr.Mithila. Actually I said at the beginning too
you have done this task very well and the reason for not chosen as the best
is the competition and the small mistakes  you have done. As you can see in
the follow there is a instruction to make pr message. And also cron job has
done by the winned candidate and it is only a plus point to him. Not your
fault.

By the way thank you very much for your participation and understanding.
Also encourage to learn and find the exact reason in the future too. It is
a great quality actually.

Thank you.
Wish you all the best.
Good night
[image: image.png]

**Pull request closed without merging**
